# src/rhosocial/activerecord/backend/impl/postgres/protocols/features.py
"""PostgreSQL features feature support protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class PostgresFeaturesSupport(Protocol):
    """PostgreSQL features feature support protocol."""

    def supports_generated_columns(self)-> bool: ...

    def supports_cte_search_cycle(self)-> bool: ...

    def supports_fetch_with_ties(self)-> bool: ...

    def supports_call_statement(self)-> bool: ...

    def supports_stored_procedure_transaction_control(self)-> bool: ...

    def supports_sql_body_functions(self)-> bool: ...

    def supports_nulls_not_distinct_unique(self)-> bool: ...

    def supports_regexp_like(self)-> bool: ...

    def supports_random_normal(self)-> bool: ...

    def supports_json_table_nested_path(self)-> bool: ...

    def supports_merge_with_cte(self)-> bool: ...

    def supports_update_returning_old(self)-> bool: ...
