# src/rhosocial/activerecord/backend/impl/postgres/protocols/view.py
"""PostgreSQL view feature support protocol."""

from typing import Any, Protocol, runtime_checkable, Tuple


@runtime_checkable
class PostgresViewSupport(Protocol):
    """PostgreSQL view feature support protocol."""

    def supports_or_replace_view(self) -> bool: ...
    def supports_create_or_replace_view(self) -> bool: ...
    def supports_if_not_exists_view(self) -> bool: ...
    def supports_temporary_view(self) -> bool: ...
    def supports_if_exists_view(self) -> bool: ...
    def supports_view_check_option(self) -> bool: ...
    def supports_cascade_view(self) -> bool: ...
    def supports_materialized_view(self) -> bool: ...
    def supports_refresh_materialized_view(self) -> bool: ...
    def supports_materialized_view_tablespace(self) -> bool: ...
    def supports_materialized_view_storage_options(self) -> bool: ...

    def format_create_view_statement(self, expr: Any) -> Tuple[str, tuple]:
        """Format CREATE VIEW statement for PostgreSQL.

        Supports TEMPORARY, OR REPLACE, column aliases, and
        WITH {LOCAL|CASCADED} CHECK OPTION.

        Args:
            expr: CreateViewExpression instance

        Returns:
            Tuple of (SQL string, parameters tuple)
        """
        ...
