# src/rhosocial/activerecord/backend/impl/postgres/protocols/view.py
"""PostgreSQL view feature support protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class PostgresViewSupport(Protocol):
    """PostgreSQL view feature support protocol."""

    def supports_or_replace_view(self) -> bool: ...
    def supports_temporary_view(self) -> bool: ...
    def supports_if_exists_view(self) -> bool: ...
    def supports_view_check_option(self) -> bool: ...
    def supports_cascade_view(self) -> bool: ...
    def supports_materialized_view(self) -> bool: ...
    def supports_refresh_materialized_view(self) -> bool: ...
    def supports_materialized_view_tablespace(self) -> bool: ...
    def supports_materialized_view_storage_options(self) -> bool: ...
