# src/rhosocial/activerecord/backend/impl/postgres/protocols/xml.py
"""PostgreSQL xml feature support protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class PostgresXMLSupport(Protocol):
    """PostgreSQL xml feature support protocol."""

    def supports_xmlparse(self)-> bool: ...

    def supports_xmlserialize(self)-> bool: ...

    def supports_xmlelement(self)-> bool: ...

    def supports_xmlattributes(self)-> bool: ...

    def supports_xmlforest(self)-> bool: ...

    def supports_xmlconcat(self)-> bool: ...

    def supports_xmlcomment(self)-> bool: ...

    def supports_xmlpi(self)-> bool: ...

    def supports_xmlroot(self)-> bool: ...

    def supports_xmlagg(self)-> bool: ...

    def supports_xmlquery(self)-> bool: ...

    def supports_xmlexists(self)-> bool: ...

    def supports_xmltable(self)-> bool: ...
