# src/rhosocial/activerecord/backend/impl/postgres/__init__.py
"""PostgreSQL backend implementation for the Python ORM.

This module provides:
- PostgreSQL synchronous backend with connection management and query execution
- PostgreSQL asynchronous backend with async/await support
- PostgreSQL-specific connection configuration
- Type mapping and value conversion
- Transaction management with savepoint support (sync and async)
- PostgreSQL dialect and expression handling
- PostgreSQL-specific type definitions and mappings

Architecture:
- PostgreSQLBackend: Synchronous implementation using psycopg
- AsyncPostgreSQLBackend: Asynchronous implementation using psycopg
- Independent from ORM frameworks - uses only native drivers"""

# Public names are resolved on first access rather than at package-execution
# time. Importing this package used to import every submodule eagerly, which
# pulled in the DB driver through ``.backend`` and made the expression classes
# unreachable without it: Python executes a parent package's ``__init__`` before
# any submodule, so ``impl.<name>.expression`` could not be imported on its own.
# The exports themselves are unchanged -- attribute access, ``__all__``, ``dir()``
# and ``from ... import *`` all behave as before.
from typing import TYPE_CHECKING

#: Public name -> (submodule that defines it, attribute name within it).
#: The two differ when the original import was aliased.
_EXPORTS = {
    "AsyncPostgresBackend": (".backend", "AsyncPostgresBackend"),
    "AsyncPostgresTransactionManager": (".transaction", "AsyncPostgresTransactionManager"),
    "Box": (".type_values.geometric", "Box"),
    "CID": (".type_values.object_identifier", "CID"),
    "Circle": (".type_values.geometric", "Circle"),
    "EnumTypeManager": (".type_values.enum", "EnumTypeManager"),
    "Line": (".type_values.geometric", "Line"),
    "LineSegment": (".type_values.geometric", "LineSegment"),
    "OID": (".type_values.object_identifier", "OID"),
    "Path": (".type_values.geometric", "Path"),
    "Point": (".type_values.geometric", "Point"),
    "Polygon": (".type_values.geometric", "Polygon"),
    "PostgresAddDomainCheckAction": (".expression.ddl", "PostgresAddDomainCheckAction"),
    "PostgresAddEnumValueAction": (".expression.ddl", "PostgresAddEnumValueAction"),
    "PostgresAddTypeAttributeAction": (".expression.ddl", "PostgresAddTypeAttributeAction"),
    "PostgresAlterDomainExpression": (".expression.ddl", "PostgresAlterDomainExpression"),
    "PostgresAlterEnumTypeAddValueExpression": (".expression.ddl", "PostgresAlterEnumTypeAddValueExpression"),
    "PostgresAlterEnumTypeRenameValueExpression": (".expression.ddl", "PostgresAlterEnumTypeRenameValueExpression"),
    "PostgresAlterTypeAttributeAction": (".expression.ddl", "PostgresAlterTypeAttributeAction"),
    "PostgresBackend": (".backend", "PostgresBackend"),
    "PostgresBaseTypeDefinition": (".expression.ddl", "PostgresBaseTypeDefinition"),
    "PostgresBigSerialType": (".expression.types", "PostgresBigSerialType"),
    "PostgresBitString": (".type_values.bit_string", "PostgresBitString"),
    "PostgresBitStringAdapter": (".adapters.bit_string", "PostgresBitStringAdapter"),
    "PostgresBitType": (".expression.types", "PostgresBitType"),
    "PostgresBoxType": (".expression.types", "PostgresBoxType"),
    "PostgresByteaType": (".expression.types", "PostgresByteaType"),
    "PostgresCIDType": (".expression.types", "PostgresCIDType"),
    "PostgresChangeDomainOwnerAction": (".expression.ddl", "PostgresChangeDomainOwnerAction"),
    "PostgresChangeTypeOwnerAction": (".expression.ddl", "PostgresChangeTypeOwnerAction"),
    "PostgresCidrType": (".expression.types", "PostgresCidrType"),
    "PostgresCircleType": (".expression.types", "PostgresCircleType"),
    "PostgresCollation": (".collation", "PostgresCollation"),
    "PostgresCompositeTypeAttribute": (".expression.ddl", "PostgresCompositeTypeAttribute"),
    "PostgresCompositeTypeDefinition": (".expression.ddl", "PostgresCompositeTypeDefinition"),
    "PostgresConnectionConfig": (".config", "PostgresConnectionConfig"),
    "PostgresCopyFormat": (".expression", "PostgresCopyFormat"),
    "PostgresCopyFromExpression": (".expression", "PostgresCopyFromExpression"),
    "PostgresCopyLogVerbosity": (".expression", "PostgresCopyLogVerbosity"),
    "PostgresCopyOnError": (".expression", "PostgresCopyOnError"),
    "PostgresCopyToExpression": (".expression", "PostgresCopyToExpression"),
    "PostgresCreateDomainExpression": (".expression.ddl", "PostgresCreateDomainExpression"),
    "PostgresCreateEnumTypeExpression": (".expression.ddl", "PostgresCreateEnumTypeExpression"),
    "PostgresCreateRangeTypeExpression": (".expression.ddl", "PostgresCreateRangeTypeExpression"),
    "PostgresDateMultirangeType": (".expression.types", "PostgresDateMultirangeType"),
    "PostgresDateRangeType": (".expression.types", "PostgresDateRangeType"),
    "PostgresDialect": (".dialect", "PostgresDialect"),
    "PostgresDropDomainCheckAction": (".expression.ddl", "PostgresDropDomainCheckAction"),
    "PostgresDropDomainExpression": (".expression.ddl", "PostgresDropDomainExpression"),
    "PostgresDropEnumTypeExpression": (".expression.ddl", "PostgresDropEnumTypeExpression"),
    "PostgresDropTypeAttributeAction": (".expression.ddl", "PostgresDropTypeAttributeAction"),
    "PostgresDropTypeExpression": (".expression.ddl", "PostgresDropTypeExpression"),
    "PostgresEnumAdapter": (".adapters", "PostgresEnumAdapter"),
    "PostgresEnumType": (".type_values", "PostgresEnumType"),
    "PostgresEnumTypeDefinition": (".expression.ddl", "PostgresEnumTypeDefinition"),
    "PostgresExplainPlanLine": (".explain", "PostgresExplainPlanLine"),
    "PostgresExplainResult": (".explain", "PostgresExplainResult"),
    "PostgresGeographyType": (".expression.types", "PostgresGeographyType"),
    "PostgresGeometry": (".type_values.postgis", "PostgresGeometry"),
    "PostgresGeometryAdapter": (".adapters.geometric", "PostgresGeometryAdapter"),
    "PostgresGeometryType": (".expression.types", "PostgresGeometryType"),
    "PostgresHalfvecType": (".expression.types", "PostgresHalfvecType"),
    "PostgresHstore": (".type_values.hstore", "PostgresHstore"),
    "PostgresHstoreAdapter": (".adapters.hstore", "PostgresHstoreAdapter"),
    "PostgresHstoreType": (".expression.types", "PostgresHstoreType"),
    "PostgresInetType": (".expression.types", "PostgresInetType"),
    "PostgresInt4MultirangeType": (".expression.types", "PostgresInt4MultirangeType"),
    "PostgresInt4RangeType": (".expression.types", "PostgresInt4RangeType"),
    "PostgresInt8MultirangeType": (".expression.types", "PostgresInt8MultirangeType"),
    "PostgresInt8RangeType": (".expression.types", "PostgresInt8RangeType"),
    "PostgresJsonPath": (".type_values.json", "PostgresJsonPath"),
    "PostgresJsonPathAdapter": (".adapters.json", "PostgresJsonPathAdapter"),
    "PostgresJsonPathType": (".expression.types", "PostgresJsonPathType"),
    "PostgresLineSegmentType": (".expression.types", "PostgresLineSegmentType"),
    "PostgresLineType": (".expression.types", "PostgresLineType"),
    "PostgresLsn": (".type_values.pg_lsn", "PostgresLsn"),
    "PostgresLsnAdapter": (".adapters.pg_lsn", "PostgresLsnAdapter"),
    "PostgresMacAddr8Type": (".expression.types", "PostgresMacAddr8Type"),
    "PostgresMacAddrType": (".expression.types", "PostgresMacAddrType"),
    "PostgresMacaddr": (".type_values.network_address", "PostgresMacaddr"),
    "PostgresMacaddr8": (".type_values.network_address", "PostgresMacaddr8"),
    "PostgresMacaddr8Adapter": (".adapters.network_address", "PostgresMacaddr8Adapter"),
    "PostgresMacaddrAdapter": (".adapters.network_address", "PostgresMacaddrAdapter"),
    "PostgresMoney": (".type_values.monetary", "PostgresMoney"),
    "PostgresMoneyAdapter": (".adapters.monetary", "PostgresMoneyAdapter"),
    "PostgresMoneyType": (".expression.types", "PostgresMoneyType"),
    "PostgresMultirange": (".type_values.range", "PostgresMultirange"),
    "PostgresMultirangeAdapter": (".adapters", "PostgresMultirangeAdapter"),
    "PostgresNumMultirangeType": (".expression.types", "PostgresNumMultirangeType"),
    "PostgresNumRangeType": (".expression.types", "PostgresNumRangeType"),
    "PostgresOIDType": (".expression.types", "PostgresOIDType"),
    "PostgresOidAdapter": (".adapters.object_identifier", "PostgresOidAdapter"),
    "PostgresPathType": (".expression.types", "PostgresPathType"),
    "PostgresPgLSNType": (".expression.types", "PostgresPgLSNType"),
    "PostgresPointType": (".expression.types", "PostgresPointType"),
    "PostgresPolygonType": (".expression.types", "PostgresPolygonType"),
    "PostgresPostGISAdapter": (".adapters.postgis", "PostgresPostGISAdapter"),
    "PostgresRange": (".type_values.range", "PostgresRange"),
    "PostgresRangeAdapter": (".adapters", "PostgresRangeAdapter"),
    "PostgresRangeTypeDefinition": (".expression.ddl", "PostgresRangeTypeDefinition"),
    "PostgresRegClassType": (".expression.types", "PostgresRegClassType"),
    "PostgresRegTypeType": (".expression.types", "PostgresRegTypeType"),
    "PostgresRenameDomainConstraintAction": (".expression.ddl", "PostgresRenameDomainConstraintAction"),
    "PostgresRenameEnumValueAction": (".expression.ddl", "PostgresRenameEnumValueAction"),
    "PostgresRenameTypeAction": (".expression.ddl", "PostgresRenameTypeAction"),
    "PostgresRenameTypeAttributeAction": (".expression.ddl", "PostgresRenameTypeAttributeAction"),
    "PostgresRepackExpression": (".expression", "PostgresRepackExpression"),
    "PostgresSerialType": (".expression.types", "PostgresSerialType"),
    "PostgresSetDomainSchemaAction": (".expression.ddl", "PostgresSetDomainSchemaAction"),
    "PostgresSetTypePropertiesAction": (".expression.ddl", "PostgresSetTypePropertiesAction"),
    "PostgresSetTypeSchemaAction": (".expression.ddl", "PostgresSetTypeSchemaAction"),
    "PostgresShellTypeDefinition": (".expression.ddl", "PostgresShellTypeDefinition"),
    "PostgresSmallSerialType": (".expression.types", "PostgresSmallSerialType"),
    "PostgresSparsevecType": (".expression.types", "PostgresSparsevecType"),
    "PostgresStorageParameter": (".storage_parameters", "PostgresStorageParameter"),
    "PostgresStorageParameterValueType": (".storage_parameters", "PostgresStorageParameterValueType"),
    "PostgresTIDType": (".expression.types", "PostgresTIDType"),
    "PostgresTSQueryType": (".expression.types", "PostgresTSQueryType"),
    "PostgresTSVectorType": (".expression.types", "PostgresTSVectorType"),
    "PostgresTidAdapter": (".adapters.object_identifier", "PostgresTidAdapter"),
    "PostgresTransactionManager": (".transaction", "PostgresTransactionManager"),
    "PostgresTsMultirangeType": (".expression.types", "PostgresTsMultirangeType"),
    "PostgresTsQuery": (".type_values.text_search", "PostgresTsQuery"),
    "PostgresTsQueryAdapter": (".adapters.text_search", "PostgresTsQueryAdapter"),
    "PostgresTsRangeType": (".expression.types", "PostgresTsRangeType"),
    "PostgresTsTzMultirangeType": (".expression.types", "PostgresTsTzMultirangeType"),
    "PostgresTsTzRangeType": (".expression.types", "PostgresTsTzRangeType"),
    "PostgresTsVector": (".type_values.text_search", "PostgresTsVector"),
    "PostgresTsVectorAdapter": (".adapters.text_search", "PostgresTsVectorAdapter"),
    "PostgresUUIDAdapter": (".adapters.uuid", "PostgresUUIDAdapter"),
    "PostgresUUIDType": (".expression.types", "PostgresUUIDType"),
    "PostgresValidateDomainConstraintAction": (".expression.ddl", "PostgresValidateDomainConstraintAction"),
    "PostgresVarBitType": (".expression.types", "PostgresVarBitType"),
    "PostgresVector": (".type_values.pgvector", "PostgresVector"),
    "PostgresVectorAdapter": (".adapters.pgvector", "PostgresVectorAdapter"),
    "PostgresVectorType": (".expression.types", "PostgresVectorType"),
    "PostgresXID8Type": (".expression.types", "PostgresXID8Type"),
    "PostgresXIDType": (".expression.types", "PostgresXIDType"),
    "PostgresXML": (".type_values.xml", "PostgresXML"),
    "PostgresXMLAdapter": (".adapters.xml", "PostgresXMLAdapter"),
    "PostgresXMLType": (".expression.types", "PostgresXMLType"),
    "PostgresXidAdapter": (".adapters.object_identifier", "PostgresXidAdapter"),
    "RegClass": (".type_values.object_identifier", "RegClass"),
    "RegCollation": (".type_values.object_identifier", "RegCollation"),
    "RegConfig": (".type_values.object_identifier", "RegConfig"),
    "RegDictionary": (".type_values.object_identifier", "RegDictionary"),
    "RegNamespace": (".type_values.object_identifier", "RegNamespace"),
    "RegOper": (".type_values.object_identifier", "RegOper"),
    "RegOperator": (".type_values.object_identifier", "RegOperator"),
    "RegProc": (".type_values.object_identifier", "RegProc"),
    "RegProcedure": (".type_values.object_identifier", "RegProcedure"),
    "RegRole": (".type_values.object_identifier", "RegRole"),
    "RegType": (".type_values.object_identifier", "RegType"),
    "TID": (".type_values.object_identifier", "TID"),
    "XID": (".type_values.object_identifier", "XID"),
    "XID8": (".type_values.object_identifier", "XID8"),
    "bit_and": (".functions", "bit_and"),
    "bit_concat": (".functions", "bit_concat"),
    "bit_count": (".functions", "bit_count"),
    "bit_get_bit": (".functions", "bit_get_bit"),
    "bit_length": (".functions", "bit_length"),
    "bit_length_func": (".functions", "bit_length_func"),
    "bit_not": (".functions", "bit_not"),
    "bit_octet_length": (".functions", "bit_octet_length"),
    "bit_or": (".functions", "bit_or"),
    "bit_set_bit": (".functions", "bit_set_bit"),
    "bit_shift_left": (".functions", "bit_shift_left"),
    "bit_shift_right": (".functions", "bit_shift_right"),
    "bit_xor": (".functions", "bit_xor"),
    "enum_first": (".functions", "enum_first"),
    "enum_ge": (".functions", "enum_ge"),
    "enum_gt": (".functions", "enum_gt"),
    "enum_last": (".functions", "enum_last"),
    "enum_le": (".functions", "enum_le"),
    "enum_lt": (".functions", "enum_lt"),
    "enum_range": (".functions", "enum_range"),
    "gen_random_uuid": (".functions", "gen_random_uuid"),
    "geometry_area": (".functions", "geometry_area"),
    "geometry_center": (".functions", "geometry_center"),
    "geometry_contained_by": (".functions", "geometry_contained_by"),
    "geometry_contains": (".functions", "geometry_contains"),
    "geometry_distance": (".functions", "geometry_distance"),
    "geometry_height": (".functions", "geometry_height"),
    "geometry_length": (".functions", "geometry_length"),
    "geometry_not_extend_left": (".functions", "geometry_not_extend_left"),
    "geometry_not_extend_right": (".functions", "geometry_not_extend_right"),
    "geometry_npoints": (".functions", "geometry_npoints"),
    "geometry_overlaps": (".functions", "geometry_overlaps"),
    "geometry_strictly_left": (".functions", "geometry_strictly_left"),
    "geometry_strictly_right": (".functions", "geometry_strictly_right"),
    "geometry_width": (".functions", "geometry_width"),
    "hstore_akeys": (".functions", "hstore_akeys"),
    "hstore_all_keys_exist": (".functions", "hstore_all_keys_exist"),
    "hstore_any_key_exists": (".functions", "hstore_any_key_exists"),
    "hstore_avals": (".functions", "hstore_avals"),
    "hstore_concat": (".functions", "hstore_concat"),
    "hstore_contained_by": (".functions", "hstore_contained_by"),
    "hstore_contains": (".functions", "hstore_contains"),
    "hstore_defined": (".functions", "hstore_defined"),
    "hstore_delete": (".functions", "hstore_delete"),
    "hstore_delete_keys": (".functions", "hstore_delete_keys"),
    "hstore_delete_pairs": (".functions", "hstore_delete_pairs"),
    "hstore_each": (".functions", "hstore_each"),
    "hstore_exist": (".functions", "hstore_exist"),
    "hstore_from_key_value": (".functions", "hstore_from_key_value"),
    "hstore_from_record": (".functions", "hstore_from_record"),
    "hstore_get_value": (".functions", "hstore_get_value"),
    "hstore_get_value_as_text": (".functions", "hstore_get_value_as_text"),
    "hstore_get_values": (".functions", "hstore_get_values"),
    "hstore_key_exists": (".functions", "hstore_key_exists"),
    "hstore_populate_record": (".functions", "hstore_populate_record"),
    "hstore_record_update": (".functions", "hstore_record_update"),
    "hstore_skeys": (".functions", "hstore_skeys"),
    "hstore_slice": (".functions", "hstore_slice"),
    "hstore_subscript_get": (".functions", "hstore_subscript_get"),
    "hstore_subscript_set": (".functions", "hstore_subscript_set"),
    "hstore_subtract_key": (".functions", "hstore_subtract_key"),
    "hstore_subtract_keys": (".functions", "hstore_subtract_keys"),
    "hstore_subtract_pairs": (".functions", "hstore_subtract_pairs"),
    "hstore_svals": (".functions", "hstore_svals"),
    "hstore_to_array": (".functions", "hstore_to_array"),
    "hstore_to_array_operator": (".functions", "hstore_to_array_operator"),
    "hstore_to_json": (".functions", "hstore_to_json"),
    "hstore_to_json_loose": (".functions", "hstore_to_json_loose"),
    "hstore_to_jsonb": (".functions", "hstore_to_jsonb"),
    "hstore_to_jsonb_loose": (".functions", "hstore_to_jsonb_loose"),
    "hstore_to_matrix": (".functions", "hstore_to_matrix"),
    "hstore_to_matrix_operator": (".functions", "hstore_to_matrix_operator"),
    "json_path_filter": (".functions", "json_path_filter"),
    "json_path_index": (".functions", "json_path_index"),
    "json_path_key": (".functions", "json_path_key"),
    "json_path_root": (".functions", "json_path_root"),
    "json_path_wildcard": (".functions", "json_path_wildcard"),
    "jsonb_path_exists": (".functions", "jsonb_path_exists"),
    "jsonb_path_match": (".functions", "jsonb_path_match"),
    "jsonb_path_query": (".functions", "jsonb_path_query"),
    "jsonb_path_query_first": (".functions", "jsonb_path_query_first"),
    "phraseto_tsquery": (".functions.text_search", "phraseto_tsquery"),
    "plainto_tsquery": (".functions.text_search", "plainto_tsquery"),
    "range_adjacent": (".functions", "range_adjacent"),
    "range_contained_by": (".functions", "range_contained_by"),
    "range_contains": (".functions", "range_contains"),
    "range_contains_range": (".functions", "range_contains_range"),
    "range_difference": (".functions", "range_difference"),
    "range_intersection": (".functions", "range_intersection"),
    "range_is_empty": (".functions", "range_is_empty"),
    "range_lower": (".functions", "range_lower"),
    "range_lower_inc": (".functions", "range_lower_inc"),
    "range_lower_inf": (".functions", "range_lower_inf"),
    "range_not_extend_left": (".functions", "range_not_extend_left"),
    "range_not_extend_right": (".functions", "range_not_extend_right"),
    "range_overlaps": (".functions", "range_overlaps"),
    "range_strictly_left_of": (".functions", "range_strictly_left_of"),
    "range_strictly_right_of": (".functions", "range_strictly_right_of"),
    "range_union": (".functions", "range_union"),
    "range_upper": (".functions", "range_upper"),
    "range_upper_inc": (".functions", "range_upper_inc"),
    "range_upper_inf": (".functions", "range_upper_inf"),
    "st_area": (".functions", "st_area"),
    "st_as_geojson": (".functions", "st_as_geojson"),
    "st_as_text": (".functions", "st_as_text"),
    "st_buffer": (".functions", "st_buffer"),
    "st_centroid": (".functions", "st_centroid"),
    "st_contains": (".functions", "st_contains"),
    "st_crosses": (".functions", "st_crosses"),
    "st_distance": (".functions", "st_distance"),
    "st_dwithin": (".functions", "st_dwithin"),
    "st_envelope": (".functions", "st_envelope"),
    "st_geog_from_text": (".functions", "st_geog_from_text"),
    "st_geom_from_text": (".functions", "st_geom_from_text"),
    "st_intersects": (".functions", "st_intersects"),
    "st_length": (".functions", "st_length"),
    "st_make_point": (".functions", "st_make_point"),
    "st_overlaps": (".functions", "st_overlaps"),
    "st_set_srid": (".functions", "st_set_srid"),
    "st_touches": (".functions", "st_touches"),
    "st_transform": (".functions", "st_transform"),
    "st_within": (".functions", "st_within"),
    "to_tsquery": (".functions.text_search", "to_tsquery"),
    "to_tsvector": (".functions.text_search", "to_tsvector"),
    "ts_headline": (".functions.text_search", "ts_headline"),
    "ts_matches": (".functions.text_search", "ts_matches"),
    "ts_matches_expr": (".functions.text_search", "ts_matches_expr"),
    "ts_rank": (".functions.text_search", "ts_rank"),
    "ts_rank_cd": (".functions.text_search", "ts_rank_cd"),
    "tsvector_concat": (".functions.text_search", "tsvector_concat"),
    "tsvector_length": (".functions.text_search", "tsvector_length"),
    "tsvector_setweight": (".functions.text_search", "tsvector_setweight"),
    "tsvector_strip": (".functions.text_search", "tsvector_strip"),
    "uuid_default_generator": (".functions", "uuid_default_generator"),
    "vector_cosine_distance": (".functions", "vector_cosine_distance"),
    "vector_cosine_similarity": (".functions", "vector_cosine_similarity"),
    "vector_inner_product": (".functions", "vector_inner_product"),
    "vector_l2_distance": (".functions", "vector_l2_distance"),
    "vector_literal": (".functions", "vector_literal"),
    "websearch_to_tsquery": (".functions.text_search", "websearch_to_tsquery"),
}

if TYPE_CHECKING:  # pragma: no cover - re-exports for type checkers
    from .backend import PostgresBackend, AsyncPostgresBackend
    from .collation import PostgresCollation  # noqa: F401
    from .config import PostgresConnectionConfig
    from .dialect import PostgresDialect
    from .storage_parameters import (  # noqa: F401
        PostgresStorageParameter,
        PostgresStorageParameterValueType,
    )
    from .transaction import PostgresTransactionManager, AsyncPostgresTransactionManager
    from .types import PostgresEnumType
    from .expression.types import (
        PostgresBigSerialType,
        PostgresBitType,
        PostgresBoxType,
        PostgresByteaType,
        PostgresCIDType,
        PostgresCircleType,
        PostgresDateMultirangeType,
        PostgresDateRangeType,
        PostgresGeographyType,
        PostgresGeometryType,
        PostgresHstoreType,
        PostgresInetType,
        PostgresInt4MultirangeType,
        PostgresInt4RangeType,
        PostgresInt8MultirangeType,
        PostgresInt8RangeType,
        PostgresJsonPathType,
        PostgresLineSegmentType,
        PostgresLineType,
        PostgresMacAddr8Type,
        PostgresMacAddrType,
        PostgresMoneyType,
        PostgresNumMultirangeType,
        PostgresNumRangeType,
        PostgresOIDType,
        PostgresPathType,
        PostgresPgLSNType,
        PostgresPointType,
        PostgresPolygonType,
        PostgresRegClassType,
        PostgresRegTypeType,
        PostgresSerialType,
        PostgresSmallSerialType,
        PostgresTIDType,
        PostgresTSQueryType,
        PostgresTSVectorType,
        PostgresTsMultirangeType,
        PostgresTsRangeType,
        PostgresTsTzMultirangeType,
        PostgresTsTzRangeType,
        PostgresUUIDType,
        PostgresVarBitType,
        PostgresVectorType,
        PostgresHalfvecType,
        PostgresSparsevecType,
        PostgresXID8Type,
        PostgresXIDType,
        PostgresXMLType,
        PostgresCidrType,
    )
    from .explain import PostgresExplainResult, PostgresExplainPlanLine
    from .expression import (
        PostgresCopyFormat,
        PostgresCopyFromExpression,
        PostgresCopyLogVerbosity,
        PostgresCopyOnError,
        PostgresCopyToExpression,
        PostgresRepackExpression,
    )
    from .expression.ddl import (
        PostgresAddDomainCheckAction,
        PostgresAddEnumValueAction,
        PostgresAddTypeAttributeAction,
        PostgresAlterDomainExpression,
        PostgresAlterEnumTypeAddValueExpression,
        PostgresAlterEnumTypeRenameValueExpression,
        PostgresAlterTypeAttributeAction,
        PostgresBaseTypeDefinition,
        PostgresChangeDomainOwnerAction,
        PostgresChangeTypeOwnerAction,
        PostgresCompositeTypeAttribute,
        PostgresCompositeTypeDefinition,
        PostgresCreateDomainExpression,
        PostgresCreateEnumTypeExpression,
        PostgresCreateRangeTypeExpression,
        PostgresDropDomainCheckAction,
        PostgresDropDomainExpression,
        PostgresDropEnumTypeExpression,
        PostgresDropTypeAttributeAction,
        PostgresDropTypeExpression,
        PostgresEnumTypeDefinition,
        PostgresRangeTypeDefinition,
        PostgresRenameDomainConstraintAction,
        PostgresRenameEnumValueAction,
        PostgresRenameTypeAction,
        PostgresRenameTypeAttributeAction,
        PostgresSetDomainSchemaAction,
        PostgresSetTypePropertiesAction,
        PostgresSetTypeSchemaAction,
        PostgresShellTypeDefinition,
        PostgresValidateDomainConstraintAction,
    )
    from .adapters import (
        PostgresEnumAdapter,
        PostgresRangeAdapter,
        PostgresMultirangeAdapter,
    )
    from .types.range import (
        PostgresRange,
        PostgresMultirange,
    )
    from .types.geometric import (
        Point,
        Line,
        LineSegment,
        Box,
        Path,
        Polygon,
        Circle,
    )
    from .adapters.geometric import PostgresGeometryAdapter
    from .types.bit_string import PostgresBitString
    from .adapters.bit_string import PostgresBitStringAdapter
    from .types.monetary import PostgresMoney
    from .adapters.monetary import PostgresMoneyAdapter
    from .types.xml import PostgresXML
    from .adapters.xml import PostgresXMLAdapter
    from .types.network_address import PostgresMacaddr, PostgresMacaddr8
    from .adapters.network_address import PostgresMacaddrAdapter, PostgresMacaddr8Adapter
    from .adapters.uuid import PostgresUUIDAdapter
    from .types.pgvector import PostgresVector
    from .adapters.pgvector import PostgresVectorAdapter
    from .types.postgis import PostgresGeometry
    from .adapters.postgis import PostgresPostGISAdapter
    from .types.hstore import PostgresHstore
    from .adapters.hstore import PostgresHstoreAdapter
    from .types.text_search import (
        PostgresTsVector,
        PostgresTsQuery,
    )
    from .functions.text_search import (
        to_tsvector,
        to_tsquery,
        plainto_tsquery,
        phraseto_tsquery,
        websearch_to_tsquery,
        ts_matches,
        ts_matches_expr,
        ts_rank,
        ts_rank_cd,
        ts_headline,
        tsvector_concat,
        tsvector_strip,
        tsvector_setweight,
        tsvector_length,
    )
    from .adapters.text_search import PostgresTsVectorAdapter, PostgresTsQueryAdapter
    from .types.pg_lsn import PostgresLsn
    from .adapters.pg_lsn import PostgresLsnAdapter
    from .types.object_identifier import (
        OID,
        RegClass,
        RegType,
        RegProc,
        RegProcedure,
        RegOper,
        RegOperator,
        RegConfig,
        RegDictionary,
        RegNamespace,
        RegRole,
        RegCollation,
        XID,
        XID8,
        CID,
        TID,
    )
    from .adapters.object_identifier import PostgresOidAdapter, PostgresXidAdapter, PostgresTidAdapter
    from .types.json import PostgresJsonPath
    from .adapters.json import PostgresJsonPathAdapter
    from .types.enum import EnumTypeManager
    from .functions import (
        # Range functions
        range_contains,
        range_contained_by,
        range_contains_range,
        range_overlaps,
        range_adjacent,
        range_strictly_left_of,
        range_strictly_right_of,
        range_not_extend_right,
        range_not_extend_left,
        range_union,
        range_intersection,
        range_difference,
        range_lower,
        range_upper,
        range_is_empty,
        range_lower_inc,
        range_upper_inc,
        range_lower_inf,
        range_upper_inf,
        # Geometry functions
        geometry_distance,
        geometry_contains,
        geometry_contained_by,
        geometry_overlaps,
        geometry_strictly_left,
        geometry_strictly_right,
        geometry_not_extend_right,
        geometry_not_extend_left,
        geometry_area,
        geometry_center,
        geometry_length,
        geometry_width,
        geometry_height,
        geometry_npoints,
        # Enum functions
        enum_range,
        enum_first,
        enum_last,
        enum_lt,
        enum_le,
        enum_gt,
        enum_ge,
        # Bit string functions
        bit_concat,
        bit_and,
        bit_or,
        bit_xor,
        bit_not,
        bit_shift_left,
        bit_shift_right,
        bit_length,
        bit_length_func,
        bit_octet_length,
        bit_get_bit,
        bit_set_bit,
        bit_count,
        # JSON functions
        json_path_root,
        json_path_key,
        json_path_index,
        json_path_wildcard,
        json_path_filter,
        jsonb_path_query,
        jsonb_path_query_first,
        jsonb_path_exists,
        jsonb_path_match,
        # pgvector functions
        vector_l2_distance,
        vector_cosine_distance,
        vector_inner_product,
        vector_cosine_similarity,
        vector_literal,
        # PostGIS functions - Construction
        st_make_point,
        st_geom_from_text,
        st_geog_from_text,
        st_set_srid,
        st_transform,
        # PostGIS functions - Predicates
        st_contains,
        st_intersects,
        st_within,
        st_dwithin,
        st_crosses,
        st_touches,
        st_overlaps,
        # PostGIS functions - Measurements
        st_distance,
        st_area,
        st_length,
        # PostGIS functions - Output
        st_as_geojson,
        st_as_text,
        # PostGIS functions - Operations
        st_buffer,
        st_envelope,
        st_centroid,
        # hstore functions - Constructors
        hstore_from_record,
        hstore_from_key_value,
        # hstore functions - Key/Value Extraction
        hstore_akeys,
        hstore_skeys,
        hstore_avals,
        hstore_svals,
        hstore_each,
        # hstore functions - Conversion
        hstore_to_array,
        hstore_to_matrix,
        hstore_to_json,
        hstore_to_jsonb,
        hstore_to_json_loose,
        hstore_to_jsonb_loose,
        # hstore functions - Subset
        hstore_slice,
        # hstore functions - Existence
        hstore_exist,
        hstore_defined,
        # hstore functions - Delete
        hstore_delete,
        hstore_delete_keys,
        hstore_delete_pairs,
        # hstore functions - Record
        hstore_populate_record,
        # hstore functions - Operators
        hstore_get_value,
        hstore_get_value_as_text,
        hstore_get_values,
        hstore_concat,
        hstore_key_exists,
        hstore_all_keys_exist,
        hstore_any_key_exists,
        hstore_contains,
        hstore_contained_by,
        hstore_subtract_key,
        hstore_subtract_keys,
        hstore_subtract_pairs,
        hstore_to_array_operator,
        hstore_to_matrix_operator,
        hstore_record_update,
        # hstore functions - Subscript
        hstore_subscript_get,
        hstore_subscript_set,
    )

__all__ = [
    "PostgresBackend",
    "AsyncPostgresBackend",
    "PostgresConnectionConfig",
    "PostgresDialect",
    "PostgresStorageParameter",
    "PostgresStorageParameterValueType",
    "PostgresTransactionManager",
    "AsyncPostgresTransactionManager",
    "PostgresEnumType",
    "PostgresEnumAdapter",
    "PostgresExplainResult",
    "PostgresExplainPlanLine",
    "PostgresCopyFormat",
    "PostgresCopyFromExpression",
    "PostgresCopyLogVerbosity",
    "PostgresCopyOnError",
    "PostgresCopyToExpression",
    "PostgresRepackExpression",
    "PostgresCompositeTypeAttribute",
    "PostgresCompositeTypeDefinition",
    "PostgresEnumTypeDefinition",
    "PostgresRangeTypeDefinition",
    "PostgresBaseTypeDefinition",
    "PostgresShellTypeDefinition",
    "PostgresRenameTypeAction",
    "PostgresSetTypeSchemaAction",
    "PostgresChangeTypeOwnerAction",
    "PostgresRenameTypeAttributeAction",
    "PostgresAddTypeAttributeAction",
    "PostgresDropTypeAttributeAction",
    "PostgresAlterTypeAttributeAction",
    "PostgresAddEnumValueAction",
    "PostgresRenameEnumValueAction",
    "PostgresSetTypePropertiesAction",
    "PostgresDropTypeExpression",
    "PostgresCreateEnumTypeExpression",
    "PostgresDropEnumTypeExpression",
    "PostgresAlterEnumTypeAddValueExpression",
    "PostgresAlterEnumTypeRenameValueExpression",
    "PostgresCreateRangeTypeExpression",
    "PostgresAddDomainCheckAction",
    "PostgresDropDomainCheckAction",
    "PostgresRenameDomainConstraintAction",
    "PostgresValidateDomainConstraintAction",
    "PostgresChangeDomainOwnerAction",
    "PostgresSetDomainSchemaAction",
    "PostgresCreateDomainExpression",
    "PostgresAlterDomainExpression",
    "PostgresDropDomainExpression",
    "PostgresRange",
    "PostgresRangeAdapter",
    "PostgresMultirange",
    "PostgresMultirangeAdapter",
    "range_contains",
    "range_contained_by",
    "range_contains_range",
    "range_overlaps",
    "range_adjacent",
    "range_strictly_left_of",
    "range_strictly_right_of",
    "range_not_extend_right",
    "range_not_extend_left",
    "range_union",
    "range_intersection",
    "range_difference",
    "range_lower",
    "range_upper",
    "range_is_empty",
    "range_lower_inc",
    "range_upper_inc",
    "range_lower_inf",
    "range_upper_inf",
    "Point",
    "Line",
    "LineSegment",
    "Box",
    "Path",
    "Polygon",
    "Circle",
    "PostgresGeometryAdapter",
    "geometry_distance",
    "geometry_contains",
    "geometry_contained_by",
    "geometry_overlaps",
    "geometry_strictly_left",
    "geometry_strictly_right",
    "geometry_not_extend_right",
    "geometry_not_extend_left",
    "geometry_area",
    "geometry_center",
    "geometry_length",
    "geometry_width",
    "geometry_height",
    "geometry_npoints",
    "PostgresBitString",
    "PostgresBitStringAdapter",
    "bit_concat",
    "bit_and",
    "bit_or",
    "bit_xor",
    "bit_not",
    "bit_shift_left",
    "bit_shift_right",
    "bit_length",
    "bit_length_func",
    "bit_octet_length",
    "bit_get_bit",
    "bit_set_bit",
    "bit_count",
    "EnumTypeManager",
    "enum_range",
    "enum_first",
    "enum_last",
    "enum_lt",
    "enum_le",
    "enum_gt",
    "enum_ge",
    "PostgresMoney",
    "PostgresMoneyAdapter",
    "PostgresXML",
    "PostgresXMLAdapter",
    "PostgresMacaddr",
    "PostgresMacaddrAdapter",
    "PostgresMacaddr8",
    "PostgresMacaddr8Adapter",
    "PostgresTsVector",
    "PostgresTsVectorAdapter",
    "PostgresTsQuery",
    "PostgresTsQueryAdapter",
    "to_tsvector",
    "to_tsquery",
    "plainto_tsquery",
    "phraseto_tsquery",
    "websearch_to_tsquery",
    "ts_matches",
    "ts_matches_expr",
    "ts_rank",
    "ts_rank_cd",
    "ts_headline",
    "tsvector_concat",
    "tsvector_strip",
    "tsvector_setweight",
    "tsvector_length",
    "PostgresLsn",
    "PostgresLsnAdapter",
    "OID",
    "RegClass",
    "RegType",
    "RegProc",
    "RegProcedure",
    "RegOper",
    "RegOperator",
    "RegConfig",
    "RegDictionary",
    "RegNamespace",
    "RegRole",
    "RegCollation",
    "XID",
    "XID8",
    "CID",
    "TID",
    "PostgresOidAdapter",
    "PostgresXidAdapter",
    "PostgresTidAdapter",
    "PostgresJsonPath",
    "PostgresJsonPathAdapter",
    "json_path_root",
    "json_path_key",
    "json_path_index",
    "json_path_wildcard",
    "json_path_filter",
    "jsonb_path_query",
    "jsonb_path_query_first",
    "jsonb_path_exists",
    "jsonb_path_match",
    "PostgresUUIDAdapter",
    "gen_random_uuid",
    "uuid_default_generator",
    "PostgresVector",
    "PostgresVectorAdapter",
    "vector_l2_distance",
    "vector_cosine_distance",
    "vector_inner_product",
    "vector_cosine_similarity",
    "vector_literal",
    "PostgresGeometry",
    "PostgresPostGISAdapter",
    "PostgresHstore",
    "PostgresHstoreAdapter",
    "st_make_point",
    "st_geom_from_text",
    "st_geog_from_text",
    "st_set_srid",
    "st_transform",
    "st_contains",
    "st_intersects",
    "st_within",
    "st_dwithin",
    "st_crosses",
    "st_touches",
    "st_overlaps",
    "st_distance",
    "st_area",
    "st_length",
    "st_as_geojson",
    "st_as_text",
    "st_buffer",
    "st_envelope",
    "st_centroid",
    "hstore_from_record",
    "hstore_from_key_value",
    "hstore_akeys",
    "hstore_skeys",
    "hstore_avals",
    "hstore_svals",
    "hstore_each",
    "hstore_to_array",
    "hstore_to_matrix",
    "hstore_to_json",
    "hstore_to_jsonb",
    "hstore_to_json_loose",
    "hstore_to_jsonb_loose",
    "hstore_slice",
    "hstore_exist",
    "hstore_defined",
    "hstore_delete",
    "hstore_delete_keys",
    "hstore_delete_pairs",
    "hstore_populate_record",
    "hstore_get_value",
    "hstore_get_value_as_text",
    "hstore_get_values",
    "hstore_concat",
    "hstore_key_exists",
    "hstore_all_keys_exist",
    "hstore_any_key_exists",
    "hstore_contains",
    "hstore_contained_by",
    "hstore_subtract_key",
    "hstore_subtract_keys",
    "hstore_subtract_pairs",
    "hstore_to_array_operator",
    "hstore_to_matrix_operator",
    "hstore_record_update",
    "hstore_subscript_get",
    "hstore_subscript_set",
    "PostgresBigSerialType",
    "PostgresBitType",
    "PostgresBoxType",
    "PostgresByteaType",
    "PostgresCIDType",
    "PostgresCircleType",
    "PostgresDateMultirangeType",
    "PostgresDateRangeType",
    "PostgresGeographyType",
    "PostgresGeometryType",
    "PostgresHstoreType",
    "PostgresInetType",
    "PostgresInt4MultirangeType",
    "PostgresInt4RangeType",
    "PostgresInt8MultirangeType",
    "PostgresInt8RangeType",
    "PostgresJsonPathType",
    "PostgresLineSegmentType",
    "PostgresLineType",
    "PostgresMacAddr8Type",
    "PostgresMacAddrType",
    "PostgresMoneyType",
    "PostgresNumMultirangeType",
    "PostgresNumRangeType",
    "PostgresOIDType",
    "PostgresPathType",
    "PostgresPgLSNType",
    "PostgresPointType",
    "PostgresPolygonType",
    "PostgresRegClassType",
    "PostgresRegTypeType",
    "PostgresSerialType",
    "PostgresSmallSerialType",
    "PostgresTIDType",
    "PostgresTSQueryType",
    "PostgresTSVectorType",
    "PostgresTsMultirangeType",
    "PostgresTsRangeType",
    "PostgresTsTzMultirangeType",
    "PostgresTsTzRangeType",
    "PostgresUUIDType",
    "PostgresVarBitType",
    "PostgresVectorType",
    "PostgresHalfvecType",
    "PostgresSparsevecType",
    "PostgresXID8Type",
    "PostgresXIDType",
    "PostgresXMLType",
    "PostgresCidrType",
]


def __getattr__(name: str):
    """Resolve a public name by importing its defining submodule once."""
    target = _EXPORTS.get(name)
    if target is not None:
        import importlib

        module_name, attr = target
        value = getattr(importlib.import_module(module_name, __name__), attr)
        globals()[name] = value  # cache, so __getattr__ runs at most once per name
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals()) | set(_EXPORTS))
