# src/rhosocial/activerecord/backend/impl/postgres/examples/sqlxml/standard_expressions.py
"""PostgreSQL SQL/XML standard expression examples.

By default this script only renders SQL and parameters. Pass --execute to run
safe SELECT examples against PostgreSQL using PGHOST / PGPORT / PGDATABASE /
PGUSER / PGPASSWORD environment variables.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Iterable, Optional, Tuple, Union

from rhosocial.activerecord.backend.expression import (
    Column,
    ColumnConstraint,
    ColumnConstraintType,
    ColumnDefinition,
    CreateTableExpression,
    DropTableExpression,
    InsertExpression,
    Literal,
    OrderByClause,
    QueryExpression,
    TableExpression,
    ValuesSource,
    XMLStandaloneOption,
    XMLTableColumn,
    xmlagg,
    xmlattributes,
    xmlcomment,
    xmlconcat,
    xmlelement,
    xmlexists,
    xmlforest,
    xmlparse,
    xmlpi,
    xmlroot,
    xmlserialize,
    xmltable,
)
from rhosocial.activerecord.backend.impl.postgres import (
    PostgresBackend,
    PostgresConnectionConfig,
    PostgresDialect,
)

SQLParam = Optional[Union[str, int, float, bool]]
SQLParams = Tuple[SQLParam, ...]
SQLQueryAndParams = Tuple[str, SQLParams]
EXAMPLE_TABLE = "sqlxml_example_items"
EXAMPLE_DIR = Path(__file__).resolve().parent


def load_xml(filename: str) -> str:
    return (EXAMPLE_DIR / filename).read_text(encoding="utf-8").strip()


class SQLXMLExample:
    def __init__(
        self,
        title: str,
        sql_and_params: SQLQueryAndParams,
        executable: bool = True,
    ):
        self.title: str = title
        self.sql_and_params: SQLQueryAndParams = sql_and_params
        self.executable: bool = executable


def text_literal(dialect: PostgresDialect, value: str) -> Literal:
    expr = Literal(dialect, value)
    expr.cast("TEXT")
    return expr


def xml_literal(dialect: PostgresDialect, value: str) -> Literal:
    expr = Literal(dialect, value)
    expr.cast("XML")
    return expr


def render(example: SQLXMLExample) -> None:
    sql, params = example.sql_and_params
    print(f"\n=== {example.title} ===")
    print(sql)
    print(f"params: {params}")


def select(dialect: PostgresDialect, expr) -> SQLQueryAndParams:
    sql, params = QueryExpression(dialect, [expr]).to_sql()
    return sql, tuple(params)


def select_from_examples(dialect: PostgresDialect, expr) -> SQLQueryAndParams:
    sql, params = QueryExpression(
        dialect,
        [expr],
        from_=TableExpression(dialect, EXAMPLE_TABLE),
    ).to_sql()
    return sql, tuple(params)


def build_examples(dialect: PostgresDialect) -> Iterable[SQLXMLExample]:
    payload = Column(dialect, "payload")
    item_id = Column(dialect, "id")
    root_xml = load_xml("root.xml")

    parsed_document = xmlparse(dialect, xml_literal(dialect, root_xml))
    parsed_content = xmlparse(
        dialect,
        xml_literal(dialect, "<item>alpha</item><item>beta</item>"),
        document=False,
    )

    yield SQLXMLExample("XMLPARSE document literal", select(dialect, parsed_document))
    yield SQLXMLExample("XMLPARSE content literal", select(dialect, parsed_content))
    yield SQLXMLExample(
        "XMLSERIALIZE content as text",
        select(dialect, xmlserialize(dialect, parsed_document, "TEXT")),
    )

    yield SQLXMLExample(
        "XMLELEMENT with XMLATTRIBUTES",
        select(
            dialect,
            xmlelement(
                dialect,
                "product",
                text_literal(dialect, "PostgreSQL"),
                attributes=xmlattributes(
                    dialect,
                    (text_literal(dialect, "pg-001"), "sku"),
                    (text_literal(dialect, "active"), "status"),
                ),
            ),
        ),
    )

    yield SQLXMLExample(
        "XMLFOREST values",
        select(
            dialect,
            xmlforest(
                dialect,
                (text_literal(dialect, "Ada"), "first_name"),
                (text_literal(dialect, "Lovelace"), "last_name"),
                (Literal(dialect, 1815), "birth_year"),
            ),
        ),
    )

    yield SQLXMLExample(
        "XMLCONCAT constructor output",
        select(
            dialect,
            xmlconcat(
                dialect,
                xmlelement(dialect, "first", text_literal(dialect, "alpha")),
                xmlelement(dialect, "second", text_literal(dialect, "beta")),
            ),
        ),
    )

    yield SQLXMLExample(
        "XMLCOMMENT and XMLPI",
        select(
            dialect,
            xmlconcat(
                dialect,
                xmlcomment(dialect, text_literal(dialect, "generated by rhosocial-activerecord")),
                xmlpi(
                    dialect,
                    "stylesheet",
                    text_literal(dialect, "type=\"text/xsl\" href=\"style.xsl\""),
                ),
            ),
        ),
    )

    yield SQLXMLExample(
        "XMLROOT with version and standalone",
        select(
            dialect,
            xmlroot(
                dialect,
                parsed_document,
                version="1.0",
                standalone=XMLStandaloneOption.YES,
            ),
        ),
    )

    yield SQLXMLExample(
        "XMLAGG over prepared table",
        select_from_examples(
            dialect,
            xmlagg(
                dialect,
                payload,
                order_by=OrderByClause(dialect, [(item_id, "ASC")]),
            ),
        ),
    )

    yield SQLXMLExample(
        "XMLEXISTS predicate",
        select(dialect, xmlexists(dialect, text_literal(dialect, "/root/item[@id=\"1\"]"), passing=[parsed_document])),
        executable=False,
    )

    yield SQLXMLExample(
        "XMLTABLE rows",
        xmltable(
            dialect,
            text_literal(dialect, "/root/item"),
            [
                XMLTableColumn("id", "INTEGER", path=text_literal(dialect, "@id")),
                XMLTableColumn("name", "TEXT", path=text_literal(dialect, "text()")),
            ],
            passing=[parsed_document],
        ).to_sql(),
        executable=False,
    )


def load_config() -> PostgresConnectionConfig:
    return PostgresConnectionConfig(
        host=os.environ.get("PGHOST", "localhost"),
        port=int(os.environ.get("PGPORT", "5432")),
        database=os.environ.get("PGDATABASE", "test_db"),
        username=os.environ.get("PGUSER", "postgres"),
        password=os.environ.get("PGPASSWORD", ""),
        sslmode=os.environ.get("PGSSLMODE", "prefer"),
    )


def execute_expression(backend: PostgresBackend, expr) -> None:
    sql, params = expr.to_sql()
    backend.execute(sql, tuple(params))


def prepare_example_data(backend: PostgresBackend, dialect: PostgresDialect) -> None:
    execute_expression(backend, DropTableExpression(dialect, EXAMPLE_TABLE, if_exists=True))
    execute_expression(
        backend,
        CreateTableExpression(
            dialect,
            EXAMPLE_TABLE,
            [
                ColumnDefinition(
                    "id",
                    "INTEGER",
                    [ColumnConstraint(ColumnConstraintType.PRIMARY_KEY)],
                ),
                ColumnDefinition(
                    "payload",
                    "XML",
                    [ColumnConstraint(ColumnConstraintType.NOT_NULL)],
                ),
            ],
        ),
    )
    execute_expression(
        backend,
        InsertExpression(
            dialect,
            EXAMPLE_TABLE,
            ValuesSource(
                dialect,
                [
                    [Literal(dialect, 1), xmlparse(dialect, xml_literal(dialect, load_xml("item_1.xml")))],
                    [Literal(dialect, 2), xmlparse(dialect, xml_literal(dialect, load_xml("item_2.xml")))],
                ],
            ),
            columns=["id", "payload"],
        ),
    )


def cleanup_example_data(backend: PostgresBackend, dialect: PostgresDialect) -> None:
    execute_expression(backend, DropTableExpression(dialect, EXAMPLE_TABLE, if_exists=True))


def run_select_examples(dialect: PostgresDialect, examples: Iterable[SQLXMLExample]) -> None:
    backend = PostgresBackend(connection_config=load_config())
    backend.connect()
    try:
        prepare_example_data(backend, dialect)
        for example in examples:
            print(f"\n=== execute: {example.title} ===")
            if not example.executable:
                print("skip execution: rendered expression is not a standalone query")
                continue
            sql, params = example.sql_and_params
            print(backend.execute(sql, params).data)
    finally:
        try:
            cleanup_example_data(backend, dialect)
        finally:
            backend.disconnect()


def main() -> None:
    execute = "--execute" in sys.argv
    dialect = PostgresDialect((16, 0, 0))
    examples = list(build_examples(dialect))

    print("PostgreSQL SQL/XML standard capability flags:")
    print(f"  XMLPARSE: {dialect.supports_xmlparse()}")
    print(f"  XMLSERIALIZE: {dialect.supports_xmlserialize()}")
    print(f"  XMLELEMENT: {dialect.supports_xmlelement()}")
    print(f"  XMLAGG: {dialect.supports_xmlagg()}")
    print(f"  XMLEXISTS: {dialect.supports_xmlexists()}")
    print(f"  XMLTABLE: {dialect.supports_xmltable()}")
    print(
        f"  XMLQUERY: {dialect.supports_xmlquery()} "
        "(not declared as PostgreSQL standard support)"
    )

    for example in examples:
        render(example)

    if execute:
        run_select_examples(dialect, examples)


if __name__ == "__main__":
    main()
