# tests/rhosocial/activerecord_postgres_test/feature/backend/test_identity_execution.py
"""Execution confirmation for PostgreSQL identity / auto-increment / SERIAL DDL.

Rendering is not execution. PostgreSQL 9 renders a well-formed
``GENERATED ... AS IDENTITY`` clause and its server rejects it with
``syntax error at or near "GENERATED"``, which is exactly the failure this
file exists to catch. Every clause is built with the expression layer, rendered
by the dialect the live backend carries, and executed against that server.

The three outcomes stay distinct, as core's helper requires:

* the server accepts -> ``ACCEPTED``;
* the server rejects SQL the expression rendered -> the helper raises, and
  that is a defect;
* the expression refuses to render (``UnsupportedFeatureError``) ->
  ``NOT_RENDERED``, which on PostgreSQL 9 is the *correct* answer for an
  identity column, not a skip.

Each verdict is preceded by a sentinel: a deliberately invalid statement must
be classified ``REJECTED``, or a null result could be read as acceptance.
"""

import pytest

from rhosocial.activerecord.base import IdentityAttribute
from rhosocial.activerecord.backend.dialect.exceptions import UnsupportedFeatureError
from rhosocial.activerecord.backend.expression.execution_testing import (
    ExecutionOutcome,
    classify_execution,
    confirm_expression_execution,
)
from rhosocial.activerecord.backend.expression.objects import Table
from rhosocial.activerecord.backend.expression.statements import (
    AutoIncrementClause,
    ColumnConstraint,
    ColumnConstraintType,
    ColumnDefinition,
    CreateTableExpression,
    DropTableExpression,
    IdentityClause,
)
from rhosocial.activerecord.backend.expression.types import IntegerType
from rhosocial.activerecord.backend.impl.postgres.dialect import PostgresDialect
from rhosocial.activerecord.backend.impl.postgres.expression.types import (
    PostgresBigSerialType,
    PostgresSerialType,
    PostgresSmallSerialType,
)


# ---------------------------------------------------------------------------
# Offline: the declaration itself
# ---------------------------------------------------------------------------


class TestIdentityProbeDeclaration:
    """The probes answer the measured boundary and the renderer agrees."""

    @pytest.mark.parametrize(
        "version,expected",
        [((9, 6, 0), False), ((10, 0, 0), True), ((14, 0, 0), True), ((18, 0, 0), True)],
        ids=["pg9", "pg10", "pg14", "pg18"],
    )
    def test_mechanism_probe_carries_the_version_boundary(self, version, expected):
        dialect = PostgresDialect(version=version)
        assert dialect.supports_identity_column() is expected

    @pytest.mark.parametrize(
        "version", [(10, 0, 0), (14, 0, 0), (18, 0, 0)], ids=["pg10", "pg14", "pg18"]
    )
    def test_every_option_probe_is_declared(self, version):
        dialect = PostgresDialect(version=version)
        for probe in (
            "supports_identity_generation_always",
            "supports_identity_start",
            "supports_identity_increment",
            "supports_identity_minvalue",
            "supports_identity_maxvalue",
            "supports_identity_cycle",
            "supports_identity_cache",
        ):
            assert getattr(dialect, probe)() is True, probe

    def test_cache_is_declared_and_no_cache_is_refused(self):
        """CACHE n is expressible; NO CACHE has no identity spelling.

        The positive spelling is accepted by the server (measured:
        ``GENERATED BY DEFAULT AS IDENTITY (CACHE 1)``), while ``NO CACHE`` is
        a syntax error there, so the negative is refused by name instead of
        being rendered or dropped.
        """
        dialect = PostgresDialect(version=(18, 0, 0))
        assert dialect.supports_identity_cache() is True
        sql, _ = dialect.format_identity_clause(IdentityClause(dialect, cache=10))
        assert "CACHE 10" in sql
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY NO CACHE"):
            dialect.format_identity_clause(IdentityClause(dialect, no_cache=True))

    def test_pg9_refuses_the_clause(self):
        """PostgreSQL 9 has no identity columns, so the formatter refuses.

        The refusal is the point: there is no fallback to SERIAL (the explicit
        SERIAL type path is covered separately and executes on every version).
        """
        dialect = PostgresDialect(version=(9, 6, 0))
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            dialect.format_identity_clause(IdentityClause(dialect))

    def test_auto_increment_marker_is_declared_false_and_refused(self):
        dialect = PostgresDialect(version=(18, 0, 0))
        assert dialect.supports_auto_increment_column() is False
        with pytest.raises(UnsupportedFeatureError, match="AUTO_INCREMENT column"):
            AutoIncrementClause(dialect).to_sql()


# ---------------------------------------------------------------------------
# Live: the rendered clause is accepted (or correctly refused) by the server
# ---------------------------------------------------------------------------


def _identity_table(dialect, table_name, **identity_kwargs):
    return CreateTableExpression(
        dialect=dialect,
        table=Table(dialect, table_name),
        columns=[
            ColumnDefinition(
                dialect,
                "id",
                IntegerType(dialect=dialect),
                attributes=[IdentityAttribute(**identity_kwargs)],
            )
        ],
    )


def _auto_increment_table(dialect, table_name):
    return CreateTableExpression(
        dialect=dialect,
        table=Table(dialect, table_name),
        columns=[
            ColumnDefinition(
                dialect,
                "id",
                IntegerType(dialect=dialect),
                constraints=[
                    ColumnConstraint(
                        dialect,
                        ColumnConstraintType.PRIMARY_KEY,
                        is_auto_increment=True,
                    )
                ],
            )
        ],
    )


def _serial_table(dialect, table_name, data_type):
    return CreateTableExpression(
        dialect=dialect,
        table=Table(dialect, table_name),
        columns=[ColumnDefinition(dialect, "id", data_type(dialect=dialect))],
    )


def _confirm(backend, expression, table_name):
    dialect = backend.dialect
    return confirm_expression_execution(
        backend,
        expression,
        teardown=[
            DropTableExpression(dialect, Table(dialect, table_name), if_exists=True)
        ],
    )


class TestIdentityExecutionConfirmation:
    """Acceptance is confirmed against the live server, per version."""

    def test_sentinel_rejected_and_control_accepted(self, postgres_backend):
        """The classifier must see both answers before any verdict is trusted."""
        assert (
            classify_execution(postgres_backend, "THIS IS NOT SQL")
            is ExecutionOutcome.REJECTED
        )
        assert (
            classify_execution(postgres_backend, "SELECT 1")
            is ExecutionOutcome.ACCEPTED
        )

    def test_bare_identity_matches_the_declaration(self, postgres_backend):
        dialect = postgres_backend.dialect
        outcome = _confirm(
            postgres_backend,
            _identity_table(dialect, "test_identity_exec_bare"),
            "test_identity_exec_bare",
        )
        if dialect.supports_identity_column():
            assert outcome is ExecutionOutcome.ACCEPTED
        else:
            assert outcome is ExecutionOutcome.NOT_RENDERED

    def test_always_with_options_matches_the_declaration(self, postgres_backend):
        dialect = postgres_backend.dialect
        outcome = _confirm(
            postgres_backend,
            _identity_table(
                dialect,
                "test_identity_exec_options",
                generation="ALWAYS",
                start=100,
                increment=5,
                minvalue=1,
                maxvalue=1000000,
                cycle=True,
            ),
            "test_identity_exec_options",
        )
        if dialect.supports_identity_column():
            assert outcome is ExecutionOutcome.ACCEPTED
        else:
            assert outcome is ExecutionOutcome.NOT_RENDERED

    def test_no_cycle_is_executable(self, postgres_backend):
        dialect = postgres_backend.dialect
        outcome = _confirm(
            postgres_backend,
            _identity_table(
                dialect, "test_identity_exec_nocycle", cycle=False
            ),
            "test_identity_exec_nocycle",
        )
        if dialect.supports_identity_column():
            assert outcome is ExecutionOutcome.ACCEPTED
        else:
            assert outcome is ExecutionOutcome.NOT_RENDERED

    def test_auto_increment_constraint_matches_the_declaration(self, postgres_backend):
        """The legacy is_auto_increment flag routes through the identity gate."""
        dialect = postgres_backend.dialect
        outcome = _confirm(
            postgres_backend,
            _auto_increment_table(dialect, "test_identity_exec_legacy"),
            "test_identity_exec_legacy",
        )
        if dialect.supports_identity_column():
            assert outcome is ExecutionOutcome.ACCEPTED
        else:
            assert outcome is ExecutionOutcome.NOT_RENDERED


class TestSerialTypeExecution:
    """SERIAL is a type, not an identity clause: it executes on every version."""

    @pytest.mark.parametrize(
        "data_type,table_suffix",
        [
            (PostgresSmallSerialType, "smallserial"),
            (PostgresSerialType, "serial"),
            (PostgresBigSerialType, "bigserial"),
        ],
        ids=["smallserial", "serial", "bigserial"],
    )
    def test_serial_type_executes(self, postgres_backend, data_type, table_suffix):
        dialect = postgres_backend.dialect
        table_name = f"test_identity_exec_{table_suffix}"
        outcome = _confirm(
            postgres_backend,
            _serial_table(dialect, table_name, data_type),
            table_name,
        )
        assert outcome is ExecutionOutcome.ACCEPTED
