# tests/rhosocial/activerecord_postgres_test/feature/backend/test_auto_increment_ddl.py
"""Regression tests for DDL compilation of auto-increment, standard types,
boolean defaults, and timestamps.

Covers bugs found in rbac cross-backend testing:
- is_auto_increment=True on PRIMARY_KEY must produce GENERATED BY DEFAULT
  AS IDENTITY (was missing — caused INSERT id=NULL NOT NULL violation).
- format_create_table_statement must return a string for all types.
- BooleanType with DEFAULT True must be accepted.
- TimestampType must map to TIMESTAMP.

The auto-increment constraint compiles to the SQL-standard identity clause, so
it is version-gated: PostgreSQL 9 must refuse it rather than render a
``GENERATED`` clause its server rejects, and the refusal must name the feature
instead of falling back to ``SERIAL`` (the SERIAL type family stays available
for users who ask for it explicitly).
"""

import pytest

from rhosocial.activerecord.backend.dialect.exceptions import UnsupportedFeatureError
from rhosocial.activerecord.backend.expression import (
    CreateTableExpression, ColumnDefinition, ColumnConstraint, ColumnConstraintType,
)
from rhosocial.activerecord.backend.expression.types import (
    BooleanType, IntegerType, TextType, TimestampType, VarCharType,
)
from rhosocial.activerecord.backend.impl.postgres.dialect import PostgresDialect
from rhosocial.activerecord.backend.expression.objects import Table


@pytest.fixture
def dialect():
    # An adapted dialect: the identity probe carries the measured version
    # boundary (PostgreSQL 10), so an un-adapted dialect cannot answer it.
    return PostgresDialect(version=(16, 0, 0))


def _pk(dialect):
    return [ColumnConstraint(dialect, ColumnConstraintType.PRIMARY_KEY, is_auto_increment=True)]


def _build_table(dialect):
    return CreateTableExpression(
        dialect=dialect, table=Table(dialect, 'test_tbl'),
        columns=[
            ColumnDefinition(dialect, "id", IntegerType(dialect=dialect), constraints=_pk(dialect)),
            ColumnDefinition(dialect, "name", TextType(dialect=dialect),
                constraints=[ColumnConstraint(dialect, ColumnConstraintType.NOT_NULL)]),
            ColumnDefinition(dialect, "flag", BooleanType(dialect=dialect),
                constraints=[ColumnConstraint(dialect, ColumnConstraintType.NOT_NULL),
                             ColumnConstraint(dialect, ColumnConstraintType.DEFAULT, default_value=True)]),
            ColumnDefinition(dialect, "code", VarCharType(length=16, dialect=dialect)),
            ColumnDefinition(dialect, "created_at", TimestampType(dialect=dialect)),
        ],
    )


class TestAutoIncrementDDL:

    def test_auto_increment_in_ddl(self, dialect):
        sql, _ = _build_table(dialect).to_sql()
        assert "GENERATED BY DEFAULT AS IDENTITY" in sql.upper(), \
            f"auto-increment missing: {sql}"

    def test_all_standard_types_compile(self, dialect):
        sql, params = _build_table(dialect).to_sql()
        assert isinstance(sql, str)
        assert isinstance(params, tuple)

    def test_boolean_default_true(self, dialect):
        expr = CreateTableExpression(
            dialect=dialect, table=Table(dialect, 'bool_test'),
            columns=[
                ColumnDefinition(dialect, "id", IntegerType(dialect=dialect), constraints=_pk(dialect)),
                ColumnDefinition(dialect, "flag", BooleanType(dialect=dialect),
                    constraints=[ColumnConstraint(dialect, ColumnConstraintType.NOT_NULL),
                                 ColumnConstraint(dialect, ColumnConstraintType.DEFAULT, default_value=True)]),
            ],
        )
        sql, _ = expr.to_sql()
        assert "BOOLEAN" in sql.upper()

    def test_timestamp_type(self, dialect):
        expr = CreateTableExpression(
            dialect=dialect, table=Table(dialect, 'ts_test'),
            columns=[
                ColumnDefinition(dialect, "id", IntegerType(dialect=dialect), constraints=_pk(dialect)),
                ColumnDefinition(dialect, "created_at", TimestampType(dialect=dialect)),
            ],
        )
        sql, _ = expr.to_sql()
        assert "TIMESTAMP" in sql.upper()


class TestAutoIncrementVersionGate:
    """The constraint compiles to an identity clause, so it carries the gate."""

    @pytest.mark.parametrize(
        "version", [(10, 0, 0), (14, 0, 0), (18, 0, 0)], ids=lambda v: str(v)
    )
    def test_identity_clause_rendered_from_pg10(self, version):
        sql, _ = _build_table(PostgresDialect(version=version)).to_sql()
        assert "GENERATED BY DEFAULT AS IDENTITY" in sql.upper()

    def test_refused_on_pg9(self):
        """PostgreSQL 9 has no identity columns: refuse, do not fall back."""
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            _build_table(PostgresDialect(version=(9, 6, 0))).to_sql()

    def test_refusal_is_not_a_serial_rewrite(self):
        """The refused request must not be silently rewritten to a SERIAL type."""
        dialect = PostgresDialect(version=(9, 6, 0))
        with pytest.raises(UnsupportedFeatureError):
            _build_table(dialect).to_sql()
        # A user who wants SERIAL asks for the type explicitly, and that path
        # is version-independent.
        from rhosocial.activerecord.backend.impl.postgres.expression.types import (
            PostgresSerialType,
        )
        serial = CreateTableExpression(
            dialect=dialect, table=Table(dialect, 'serial_tbl'),
            columns=[ColumnDefinition(dialect, "id", PostgresSerialType(dialect=dialect))],
        )
        sql, _ = serial.to_sql()
        assert "SERIAL" in sql.upper()
