# src/rhosocial/activerecord/backend/impl/postgres/expression/__init__.py
"""
PostgreSQL-specific expression classes.

This module provides expression classes that are specific to PostgreSQL,
such as advisory lock expressions, DDL statements, and row-level locking support.

Directory structure:
- advisory/    - Advisory lock expressions
- locking.py   - Lock strength expressions
- ddl/         - DDL statement expressions
"""

from .advisory import (
    PostgresAdvisoryLockExpression,
    PostgresAdvisoryUnlockExpression,
    PostgresAdvisoryUnlockAllExpression,
    PostgresTryAdvisoryLockExpression,
    AdvisoryLockType,
)
from .locking import LockStrength
from .ddl import (
    PostgresVacuumExpression,
    PostgresAnalyzeExpression,
    PostgresCreatePartitionExpression,
    PostgresDetachPartitionExpression,
    PostgresAttachPartitionExpression,
    PostgresPartitionMetadataExpression,
    PostgresAlterIndexExpression,
    PostgresAlterIndexActionType,
    PostgresReindexExpression,
    PostgresCreateStatisticsExpression,
    PostgresDropStatisticsExpression,
    PostgresCommentExpression,
    PostgresRefreshMaterializedViewExpression,
    PostgresCreateEnumTypeExpression,
    PostgresDropEnumTypeExpression,
    PostgresAlterEnumAddValueExpression,
    PostgresAlterEnumTypeAddValueExpression,
    PostgresAlterEnumTypeRenameValueExpression,
    PostgresCreateRangeTypeExpression,
    PostgresCreateExtensionExpression,
    PostgresDropExtensionExpression,
    PostgresPgPartmanCreateParentExpression,
    PostgresPgPartmanRunMaintenanceExpression,
    PostgresPgPartmanUpdateConfigExpression,
    PostgresPgPartmanDeleteConfigExpression,
)

# DataType subclasses for DDL
from .types import (
    PostgresBigSerialType,
    PostgresBitType,
    PostgresBoxType,
    PostgresByteaType,
    PostgresCIDType,
    PostgresCircleType,
    PostgresDateMultirangeType,
    PostgresDateRangeType,
    PostgresGeographyType,
    PostgresGeometryType,
    PostgresHstoreType,
    PostgresInetType,
    PostgresInt4MultirangeType,
    PostgresInt4RangeType,
    PostgresInt8MultirangeType,
    PostgresInt8RangeType,
    PostgresJsonPathType,
    PostgresLineSegmentType,
    PostgresLineType,
    PostgresMacAddr8Type,
    PostgresMacAddrType,
    PostgresMoneyType,
    PostgresNumMultirangeType,
    PostgresNumRangeType,
    PostgresOIDType,
    PostgresPathType,
    PostgresPgLSNType,
    PostgresPointType,
    PostgresPolygonType,
    PostgresRegClassType,
    PostgresRegTypeType,
    PostgresSerialType,
    PostgresSmallSerialType,
    PostgresTIDType,
    PostgresTSQueryType,
    PostgresTSVectorType,
    PostgresTsMultirangeType,
    PostgresTsRangeType,
    PostgresTsTzMultirangeType,
    PostgresTsTzRangeType,
    PostgresUUIDType,
    PostgresVarBitType,
    PostgresVectorType,
    PostgresXID8Type,
    PostgresXIDType,
    PostgresXMLType,
    PostgresCidrType,
)

__all__ = [
    # advisory
    "PostgresAdvisoryLockExpression",
    "PostgresAdvisoryUnlockExpression",
    "PostgresAdvisoryUnlockAllExpression",
    "PostgresTryAdvisoryLockExpression",
    "AdvisoryLockType",
    # locking
    "LockStrength",
    # ddl
    "PostgresVacuumExpression",
    "PostgresAnalyzeExpression",
    "PostgresCreatePartitionExpression",
    "PostgresDetachPartitionExpression",
    "PostgresAttachPartitionExpression",
    "PostgresPartitionMetadataExpression",
    "PostgresAlterIndexExpression",
    "PostgresAlterIndexActionType",
    "PostgresReindexExpression",
    "PostgresCreateStatisticsExpression",
    "PostgresDropStatisticsExpression",
    "PostgresCommentExpression",
    "PostgresRefreshMaterializedViewExpression",
    "PostgresCreateEnumTypeExpression",
    "PostgresDropEnumTypeExpression",
    "PostgresAlterEnumAddValueExpression",
    "PostgresAlterEnumTypeAddValueExpression",
    "PostgresAlterEnumTypeRenameValueExpression",
    "PostgresCreateRangeTypeExpression",
    "PostgresCreateExtensionExpression",
    "PostgresDropExtensionExpression",
    "PostgresPgPartmanCreateParentExpression",
    "PostgresPgPartmanRunMaintenanceExpression",
    "PostgresPgPartmanUpdateConfigExpression",
    "PostgresPgPartmanDeleteConfigExpression",
    # DataType subclasses for DDL
    "PostgresBigSerialType",
    "PostgresBitType",
    "PostgresBoxType",
    "PostgresByteaType",
    "PostgresCIDType",
    "PostgresCircleType",
    "PostgresDateMultirangeType",
    "PostgresDateRangeType",
    "PostgresGeographyType",
    "PostgresGeometryType",
    "PostgresHstoreType",
    "PostgresInetType",
    "PostgresInt4MultirangeType",
    "PostgresInt4RangeType",
    "PostgresInt8MultirangeType",
    "PostgresInt8RangeType",
    "PostgresJsonPathType",
    "PostgresLineSegmentType",
    "PostgresLineType",
    "PostgresMacAddr8Type",
    "PostgresMacAddrType",
    "PostgresMoneyType",
    "PostgresNumMultirangeType",
    "PostgresNumRangeType",
    "PostgresOIDType",
    "PostgresPathType",
    "PostgresPgLSNType",
    "PostgresPointType",
    "PostgresPolygonType",
    "PostgresRegClassType",
    "PostgresRegTypeType",
    "PostgresSerialType",
    "PostgresSmallSerialType",
    "PostgresTIDType",
    "PostgresTSQueryType",
    "PostgresTSVectorType",
    "PostgresTsMultirangeType",
    "PostgresTsRangeType",
    "PostgresTsTzMultirangeType",
    "PostgresTsTzRangeType",
    "PostgresUUIDType",
    "PostgresVarBitType",
    "PostgresVectorType",
    "PostgresXID8Type",
    "PostgresXIDType",
    "PostgresXMLType",
    "PostgresCidrType",
]
