# src/rhosocial/activerecord/backend/impl/postgres/mixins/identity_column.py
"""PostgreSQL identity column feature support implementation.

PostgreSQL has the SQL-standard ``GENERATED {ALWAYS|BY DEFAULT} AS IDENTITY``
column clause since version 10. The boundary is measured, not assumed: on
PostgreSQL 9 the live server rejects the clause with ``syntax error at or near
"GENERATED"``, while 10 through 19 all accept it -- bare, ``ALWAYS``, and with
sequence options. The generation mode and every sequence option belong to the
same synopsis, so the six parameter probes are version-independent and answer
``True``; only the mechanism probe carries the version boundary.

PostgreSQL has no fallback to ``SERIAL``: ``SERIAL`` is a *type*, carried by
:class:`~...expression.types.PostgresSerialType` and its siblings, not an
identity clause. A user who wants SERIAL asks for that type explicitly; a
PostgreSQL 9 server that is asked for an identity column is refused rather
than handed a type it did not ask for.

These probes mirror
:class:`~...protocols.identity_column.PostgresIdentitySupport`. The protocol
and this mixin are held in step by ``TestProtocolMixinForwardCoverage`` and
``TestProtocolMixinReverseCoverage`` in ``test_postgres_protocol_conformance``,
which fail if a switch is declared in one and not the other.
"""

from typing import Tuple, TYPE_CHECKING

from rhosocial.activerecord.backend.dialect.mixins import IdentityColumnMixin

if TYPE_CHECKING:
    from rhosocial.activerecord.backend.expression.statements.ddl_table import (
        IdentityClause,
    )


class PostgresIdentityColumnMixin(IdentityColumnMixin):
    """PostgreSQL identity column override implementation.

    The formatter itself stays core's: PostgreSQL uses the SQL-standard
    spelling, so ``format_identity_clause`` delegates rather than restating the
    gating. It is overridden only for the one spelling the identity synopsis
    lacks: ``NO CACHE``. The option's positive form is supported --
    ``GENERATED BY DEFAULT AS IDENTITY (CACHE 1)`` is accepted (measured on
    PostgreSQL 16) -- while ``NO CACHE`` is a syntax error there
    (``syntax error at or near "CACHE"``), so ``supports_identity_cache()``
    answers True and ``no_cache=True`` is refused by name instead of rendered.
    """

    def supports_identity_column(self) -> bool:
        """Whether ``GENERATED ... AS IDENTITY`` can be used.

        ``True`` from PostgreSQL 10 on. PostgreSQL 9 has no identity columns:
        the live server rejects the clause with a syntax error, so the
        formatter must refuse rather than render it.
        """
        return self.version >= (10, 0, 0)

    def supports_identity_generation_always(self) -> bool:
        """``GENERATED ALWAYS AS IDENTITY`` is in the PostgreSQL synopsis."""
        return True

    def supports_identity_start(self) -> bool:
        """``START WITH`` is a sequence option of the identity clause."""
        return True

    def supports_identity_increment(self) -> bool:
        """``INCREMENT BY`` is a sequence option of the identity clause."""
        return True

    def supports_identity_minvalue(self) -> bool:
        """``MINVALUE`` is a sequence option of the identity clause."""
        return True

    def supports_identity_maxvalue(self) -> bool:
        """``MAXVALUE`` is a sequence option of the identity clause."""
        return True

    def supports_identity_cycle(self) -> bool:
        """``CYCLE`` / ``NO CYCLE`` is a sequence option of the identity clause."""
        return True

    def supports_identity_cache(self) -> bool:
        """``CACHE n`` is a sequence option of the identity clause.

        ``GENERATED ... AS IDENTITY (CACHE 1)`` is accepted (measured on
        PostgreSQL 16). The option's negative spelling, ``NO CACHE``, has no
        identity form; :meth:`format_identity_clause` refuses it by name.
        """
        return True

    def format_identity_clause(self, expr: "IdentityClause") -> Tuple[str, tuple]:
        """Render the identity clause, refusing the unspellable negative.

        Delegates to the core formatter so the option gating and spelling
        hooks stay in one place. ``no_cache`` is the one spelling PostgreSQL's
        synopsis lacks; it is refused by name rather than rendered.
        """
        if expr.no_cache:
            from rhosocial.activerecord.backend.dialect.exceptions import (
                UnsupportedFeatureError,
            )

            raise UnsupportedFeatureError(
                self.name,
                "IDENTITY NO CACHE",
                f"{self.name} has no NO CACHE identity spelling; cache=1 is "
                f"the uncached form. The CACHE option itself is supported.",
            )
        return super().format_identity_clause(expr)
