# tests/rhosocial/activerecord_postgres_test/feature/backend/ddl/test_default_model_ddl.py
"""Default-type model rendering — PostgreSQL.

``DefaultUser`` declares plain Python types with no ``UseSqlType``; PostgreSQL
derives the column types via its own suggestion mapping (e.g. ``dict`` →
``JSONB``). Dialect instantiation needs no DB server; only ``to_sql()`` is
exercised here.
"""

from rhosocial.activerecord.backend.impl.postgres.dialect import PostgresDialect
from rhosocial.activerecord.examples.ddl_default_types import DefaultUser


def _render() -> str:
    sql, _ = DefaultUser.generate_create_table(dialect=PostgresDialect()).to_sql()
    return sql


def test_default_user_has_no_explicit_sql_types():
    assert DefaultUser.__table_field_sql_types__ == {}


def test_postgres_default_user_ddl_columns():
    sql = _render()
    assert 'CREATE TABLE "default_users"' in sql
    assert '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in sql
    assert '"username" TEXT NOT NULL' in sql
    assert '"email" TEXT NOT NULL' in sql
    assert '"is_active" BOOLEAN NOT NULL' in sql
    assert '"balance" DOUBLE PRECISION NOT NULL' in sql
    assert '"created_at" TIMESTAMP NOT NULL' in sql
    assert '"metadata" JSONB NOT NULL' in sql
    assert '"avatar" BYTEA NOT NULL' in sql
    assert '"birthday" DATE' in sql